import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

class EmailService:
    """郵件服務類，用於發送半導體市場報告和警報"""
    
    def __init__(self):
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        self.email_user = os.getenv("EMAIL_USER")
        self.email_password = os.getenv("EMAIL_PASSWORD")
        self.recipient_email = os.getenv("RECIPIENT_EMAIL")
        
        # Debug: 檢查密碼是否正確讀取
        if self.email_password:
            print(f"🔐 DEBUG: Password loaded, length: {len(self.email_password)} characters")
            print(f"🔐 DEBUG: Password starts with: '{self.email_password[:3]}...'")
        
        if not all([self.email_user, self.email_password, self.recipient_email]):
            print("⚠️  Warning: Email credentials not fully configured")
            print("   Please set EMAIL_USER, EMAIL_PASSWORD, RECIPIENT_EMAIL in .env file")
        else:
            print(f"✅ Email credentials loaded: {self.email_user} -> {self.recipient_email}")
    
    def send_hourly_report(self, market_analysis: str) -> bool:
        """發送整點市場報告"""
        current_time = datetime.now().strftime("%Y-%m-%d %H:00")
        
        # 將 Markdown 轉換為 HTML 格式
        from .markdown_processor import markdown_processor
        html_analysis = markdown_processor.process_for_html_chat(market_analysis)
        
        subject = f"📊 Semiconductor Market Hourly Report - {current_time}"
        
        html_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 800px; margin: 0 auto; padding: 20px;">
                    <h1 style="color: #2E86AB; border-bottom: 2px solid #2E86AB; padding-bottom: 10px;">
                        🏭 Semiconductor Market Intelligence Report
                    </h1>
                    
                    <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0;">
                        <h2 style="color: #495057; margin-top: 0;">📈 Market Summary ({current_time})</h2>
                        <div style="background-color: white; padding: 15px; border-radius: 5px; font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6;">
{html_analysis}
                        </div>
                    </div>
                    
                    <div style="background-color: #e9ecef; padding: 10px; border-radius: 5px; margin-top: 20px; text-align: center; font-size: 12px; color: #6c757d;">
                        <p>🤖 Generated by Semiconductor Market Intelligence Agent</p>
                        <p>📧 Automated hourly report delivered at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
                    </div>
                </div>
            </body>
        </html>
        """
        
        return self._send_email(subject, html_body, email_type="hourly_report")
    
    def send_volatility_alert(self, stock_alerts: list) -> bool:
        """發送股價大幅波動警報"""
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        subject = f"🚨 ALERT: Semiconductor Stock Volatility Detected - {current_time}"
        
        # 構建警報內容
        alert_content = ""
        for alert in stock_alerts:
            company = alert.get('company', 'Unknown')
            symbol = alert.get('symbol', 'N/A')
            change_percent = alert.get('change_percent', 0)
            current_price = alert.get('current_price', 'N/A')
            previous_price = alert.get('previous_price', 'N/A')
            trigger_reason = alert.get('trigger_reason', 'High volatility')
            time_period = alert.get('time_period', 'recent period')
            llm_analysis = alert.get('llm_analysis', '')
            severity = alert.get('severity', 'high')
            
            # 根據嚴重程度設定顏色
            severity_color = '#dc3545' if severity == 'extreme' else '#fd7e14'
            
            alert_content += f"""
            <div style="border-left: 4px solid {severity_color}; padding-left: 15px; margin: 20px 0; background-color: #f8f9fa; border-radius: 0 8px 8px 0;">
                <h3 style="color: {severity_color}; margin: 0 0 10px 0;">{company} ({symbol})</h3>
                
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; margin-bottom: 15px;">
                    <div>
                        <p style="margin: 5px 0;"><strong>Current Price:</strong> ${current_price}</p>
                        <p style="margin: 5px 0;"><strong>Previous Price:</strong> ${previous_price}</p>
                    </div>
                    <div>
                        <p style="margin: 5px 0;"><strong>Change:</strong> <span style="color: {'red' if change_percent < 0 else 'green'}; font-weight: bold; font-size: 16px;">{change_percent:+.2f}%</span></p>
                        <p style="margin: 5px 0;"><strong>Period:</strong> {time_period}</p>
                    </div>
                </div>
                
                <p style="margin: 5px 0; font-size: 14px; color: #6c757d;"><strong>Trigger:</strong> {trigger_reason}</p>
                
                {f'''
                <div style="background-color: #e3f2fd; padding: 12px; border-radius: 6px; margin-top: 15px; border-left: 3px solid #2196f3;">
                    <h4 style="color: #1976d2; margin: 0 0 8px 0; font-size: 14px;">🤖 AI Analysis</h4>
                    <p style="margin: 0; font-size: 13px; line-height: 1.5;">{llm_analysis}</p>
                </div>
                ''' if llm_analysis else ''}
            </div>
            """
        
        html_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 800px; margin: 0 auto; padding: 20px;">
                    <h1 style="color: #dc3545; border-bottom: 2px solid #dc3545; padding-bottom: 10px;">
                        🚨 Semiconductor Stock Volatility Alert
                    </h1>
                    
                    <div style="background-color: #f8d7da; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #f5c6cb;">
                        <h2 style="color: #721c24; margin-top: 0;">⚠️ High Volatility Detected</h2>
                        <p style="margin-bottom: 0;">The following semiconductor stocks have experienced significant price movements in short timeframes:</p>
                    </div>
                    
                    <div style="background-color: #fff; border-radius: 8px; border: 1px solid #dee2e6;">
                        {alert_content}
                    </div>
                    
                    <div style="background-color: #d1ecf1; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #bee5eb;">
                        <h3 style="color: #0c5460; margin-top: 0;">📋 Recommended Actions</h3>
                        <ul style="margin: 0; padding-left: 20px;">
                            <li>Review the AI analysis for potential causes</li>
                            <li>Check trading volumes and market sentiment</li>
                            <li>Monitor news sources for breaking developments</li>
                            <li>Consider portfolio risk management if needed</li>
                            <li>Watch for continued volatility in the next period</li>
                        </ul>
                    </div>
                    
                    <div style="background-color: #fff3cd; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #ffeaa7;">
                        <h3 style="color: #856404; margin-top: 0;">⚙️ Alert Configuration</h3>
                        <ul style="margin: 0; padding-left: 20px; color: #856404;">
                            <li><strong>High Volatility:</strong> ≥5% movement in 5 minutes</li>
                            <li><strong>Extreme Volatility:</strong> ≥10% movement in 5 minutes</li>
                            <li><strong>Monitoring Frequency:</strong> Every 5 minutes</li>
                            <li><strong>AI Analysis:</strong> Powered by ASI:One LLM</li>
                        </ul>
                    </div>
                    
                    <div style="background-color: #e9ecef; padding: 10px; border-radius: 5px; margin-top: 20px; text-align: center; font-size: 12px; color: #6c757d;">
                        <p>🤖 Generated by Semiconductor Market Intelligence Agent</p>
                        <p>⏰ Alert triggered at {current_time}</p>
                        <p>🔍 This alert compares prices from 5 minutes ago vs current prices</p>
                    </div>
                </div>
            </body>
        </html>
        """
        
        return self._send_email(subject, html_body, email_type="volatility_alert")
    
    def send_startup_notification(self) -> bool:
        """發送系統啟動通知郵件"""
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        subject = f"🚀 System Startup: Semiconductor Market Intelligence Agent - {current_time}"
        
        html_body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <div style="max-width: 800px; margin: 0 auto; padding: 20px;">
                    <h1 style="color: #28a745; border-bottom: 2px solid #28a745; padding-bottom: 10px;">
                        🚀 System Startup Notification
                    </h1>
                    
                    <div style="background-color: #d4edda; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #c3e6cb;">
                        <h2 style="color: #155724; margin-top: 0;">✅ Agent Successfully Started</h2>
                        <p style="margin-bottom: 0;"><strong>Semiconductor Market Intelligence Agent is now online and ready!</strong></p>
                    </div>
                    
                    <div style="background-color: #fff; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6; margin: 20px 0;">
                        <h3 style="color: #495057; margin-top: 0;">📊 System Information</h3>
                        <ul style="margin: 0; padding-left: 20px;">
                            <li><strong>Startup Time:</strong> {current_time}</li>
                            <li><strong>Email Service:</strong> ✅ Configured and Working</li>
                            <li><strong>Scheduled Tasks:</strong> ✅ Automatically Started</li>
                            <li><strong>Stock Monitor:</strong> ✅ Monitoring 9 Companies</li>
                            <li><strong>Knowledge Graph:</strong> ✅ Initialized</li>
                        </ul>
                    </div>
                    
                    <div style="background-color: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0;">
                        <h3 style="color: #495057; margin-top: 0;">🔧 Active Services</h3>
                        <div style="display: flex; flex-wrap: wrap; gap: 10px;">
                            <div style="background-color: #007bff; color: white; padding: 8px 12px; border-radius: 5px; font-size: 14px;">
                                📊 Hourly Reports
                            </div>
                            <div style="background-color: #dc3545; color: white; padding: 8px 12px; border-radius: 5px; font-size: 14px;">
                                🚨 Volatility Alerts
                            </div>
                            <div style="background-color: #28a745; color: white; padding: 8px 12px; border-radius: 5px; font-size: 14px;">
                                📰 News Analysis
                            </div>
                            <div style="background-color: #17a2b8; color: white; padding: 8px 12px; border-radius: 5px; font-size: 14px;">
                                💹 Stock Monitoring
                            </div>
                        </div>
                    </div>
                    
                    <div style="background-color: #fff3cd; padding: 15px; border-radius: 8px; margin: 20px 0; border: 1px solid #ffeaa7;">
                        <h3 style="color: #856404; margin-top: 0;">⏰ What to Expect</h3>
                        <ul style="margin: 0; padding-left: 20px; color: #856404;">
                            <li>📊 Hourly market reports every hour at :00 minutes</li>
                            <li>🚨 Volatility alerts when stock movements exceed 5%</li>
                            <li>📈 Continuous monitoring of NVIDIA, TSMC, Intel, AMD, and more</li>
                            <li>💬 Natural language queries about semiconductor market trends</li>
                        </ul>
                    </div>
                    
                    <div style="text-align: center; padding: 20px; background-color: #e9ecef; border-radius: 8px; margin-top: 20px;">
                        <h3 style="color: #495057; margin-top: 0;">🎯 Ready for Action</h3>
                        <p style="margin: 10px 0; color: #6c757d;">Your AI-powered semiconductor market analyst is now monitoring the markets 24/7</p>
                    </div>
                    
                    <div style="background-color: #e9ecef; padding: 10px; border-radius: 5px; margin-top: 20px; text-align: center; font-size: 12px; color: #6c757d;">
                        <p>🤖 Generated by Semiconductor Market Intelligence Agent</p>
                        <p>📧 System startup notification sent at {current_time}</p>
                    </div>
                </div>
            </body>
        </html>
        """
        
        return self._send_email(subject, html_body, email_type="startup_notification")

    def _send_email(self, subject: str, html_body: str, email_type: str) -> bool:
        """發送郵件的內部方法"""
        if not all([self.email_user, self.email_password, self.recipient_email]):
            print(f"❌ Cannot send {email_type}: Email credentials not configured")
            return False
        
        try:
            # 創建郵件
            msg = MIMEMultipart('alternative')
            msg['From'] = self.email_user
            msg['To'] = self.recipient_email
            msg['Subject'] = subject
            
            # 添加HTML內容
            html_part = MIMEText(html_body, 'html')
            msg.attach(html_part)
            
            # 發送郵件
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.email_user, self.email_password)
                server.send_message(msg)
            
            print(f"✅ {email_type} email sent successfully to {self.recipient_email}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to send {email_type} email: {e}")
            return False
    
    def test_email_connection(self) -> bool:
        """測試郵件連接"""
        test_subject = "🧪 Test Email from Semiconductor Market Agent"
        test_body = """
        <html>
            <body style="font-family: Arial, sans-serif;">
                <h2>✅ Email Configuration Test</h2>
                <p>If you receive this email, your email configuration is working correctly!</p>
                <p><strong>Timestamp:</strong> {}</p>
            </body>
        </html>
        """.format(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        
        return self._send_email(test_subject, test_body, email_type="test")

# 全局實例
email_service = EmailService()